import { getDb } from "../api/queries/connection";
import { species } from "./schema";

// Species data converted from 外贸价格表.xlsx (2026-07-11)
const rows: (typeof species.$inferInsert)[] = [
  // ---- Chinese Reptiles: snakes ----
  { category: "chinese_snake", groupName: "Ptyas mucosus", chineseName: "滑鼠蛇", latinName: "Ptyas mucosus", morph: "Primary color", size: "Baby / Adult", priceUsd: "50", stock: 20, featured: true },
  { category: "chinese_snake", groupName: "Ptyas mucosus", chineseName: "滑鼠蛇", latinName: "Ptyas mucosus", morph: "Albino Lavender Pied", size: "Subadult", priceUsd: "3000/pair", stock: 2 },
  { category: "chinese_snake", groupName: "Ptyas mucosus", chineseName: "滑鼠蛇", latinName: "Ptyas mucosus", morph: "Albino", size: "Baby", priceUsd: "150", stock: 10 },
  { category: "chinese_snake", groupName: "Ptyas mucosus", chineseName: "滑鼠蛇", latinName: "Ptyas mucosus", morph: "Albino", size: "Adult", priceUsd: "400", stock: 5 },
  { category: "chinese_snake", groupName: "Ptyas mucosus", chineseName: "滑鼠蛇", latinName: "Ptyas mucosus", morph: "White Edge", size: "Baby", priceUsd: "300", stock: 6 },
  { category: "chinese_snake", groupName: "Ptyas mucosus", chineseName: "滑鼠蛇", latinName: "Ptyas mucosus", morph: "White Edge", size: "Adult", priceUsd: "600", stock: 4 },
  { category: "chinese_snake", groupName: "Ptyas mucosus", chineseName: "滑鼠蛇", latinName: "Ptyas mucosus", morph: "Premium High Side", size: "Adult", priceUsd: "3000", showPrice: false, stock: 1 },
  { category: "chinese_snake", groupName: "Ptyas mucosus", chineseName: "滑鼠蛇", latinName: "Ptyas mucosus", morph: "Scaleless", size: "Baby", priceUsd: "600", stock: 3, featured: true },
  { category: "chinese_snake", groupName: "Ptyas mucosus", chineseName: "滑鼠蛇", latinName: "Ptyas mucosus", morph: "Pied", size: "Adult", priceUsd: "8000", showPrice: false, stock: 1 },
  { category: "chinese_snake", groupName: "Ptyas mucosus", chineseName: "滑鼠蛇", latinName: "Ptyas mucosus", morph: "Blizzard", size: "Adult", priceUsd: "8000", showPrice: false, stock: 1 },
  { category: "chinese_snake", groupName: "Ptyas mucosus", chineseName: "滑鼠蛇", latinName: "Ptyas mucosus", morph: "Patternless", size: "Baby", priceUsd: "500", stock: 3 },
  { category: "chinese_snake", groupName: "Elaphe carinata", chineseName: "王锦蛇", latinName: "Elaphe carinata", morph: "Primary color", size: "Baby", priceUsd: "50", stock: 30 },
  { category: "chinese_snake", groupName: "Elaphe carinata", chineseName: "王锦蛇", latinName: "Elaphe carinata", morph: "Primary color", size: "Adult", priceUsd: "100", stock: 20 },
  { category: "chinese_snake", groupName: "Elaphe carinata", chineseName: "王锦蛇", latinName: "Elaphe carinata", morph: "AX", size: "Adult", priceUsd: "500", stock: 4 },
  { category: "chinese_snake", groupName: "Elaphe carinata", chineseName: "王锦蛇", latinName: "Elaphe carinata", morph: "AN", size: "Adult", priceUsd: "400", stock: 4 },
  { category: "chinese_snake", groupName: "Elaphe carinata", chineseName: "王锦蛇", latinName: "Elaphe carinata", morph: "High Yellow", size: "Adult", priceUsd: "300", stock: 6 },
  { category: "chinese_snake", groupName: "Elaphe carinata", chineseName: "王锦蛇", latinName: "Elaphe carinata", morph: "High Black", size: "Adult", priceUsd: "300", stock: 6 },
  { category: "chinese_snake", groupName: "Elaphe carinata", chineseName: "王锦蛇", latinName: "Elaphe carinata", morph: "High White", size: "Adult", priceUsd: "300", stock: 6 },
  { category: "chinese_snake", groupName: "Elaphe carinata", chineseName: "王锦蛇", latinName: "Elaphe carinata", morph: "Deqin", size: "Adult", priceUsd: "300", stock: 3 },
  { category: "chinese_snake", groupName: "Elaphe carinata", chineseName: "王锦蛇", latinName: "Elaphe carinata", morph: "Coast", size: "Adult", priceUsd: "500", stock: 3 },
  { category: "chinese_snake", groupName: "Elaphe carinata", chineseName: "王锦蛇", latinName: "Elaphe carinata", morph: "Hengduan Mountains", size: "Adult", priceUsd: "400", stock: 3 },
  { category: "chinese_snake", groupName: "Elaphe carinata", chineseName: "王锦蛇", latinName: "Elaphe carinata", morph: "Eclipse / Eclipse AN", size: "Adult / Baby", priceUsd: "2000", showPrice: false, stock: 2 },
  { category: "chinese_snake", groupName: "Elaphe carinata", chineseName: "王锦蛇", latinName: "Elaphe carinata", morph: "Scaleless", size: "Baby", priceUsd: "7000", showPrice: false, stock: 1, featured: true },
  { category: "chinese_snake", groupName: "Elaphe carinata", chineseName: "王锦蛇", latinName: "Elaphe carinata", morph: "Scaleless het Cotton", size: "Baby", priceUsd: "8000", showPrice: false, stock: 1 },
  { category: "chinese_snake", groupName: "Elaphe carinata", chineseName: "王锦蛇", latinName: "Elaphe carinata", morph: "Scaleless Cotton", size: "Baby", priceUsd: "12000", showPrice: false, stock: 1 },
  { category: "chinese_snake", groupName: "Ptyas dhumnades", chineseName: "乌梢蛇", latinName: "Ptyas dhumnades", morph: "Primary color", size: "Baby", priceUsd: "20", stock: 50 },
  { category: "chinese_snake", groupName: "Ptyas dhumnades", chineseName: "乌梢蛇", latinName: "Ptyas dhumnades", morph: "Primary color", size: "Adult", priceUsd: "100", stock: 20 },
  { category: "chinese_snake", groupName: "Ptyas nigromarginatus", chineseName: "黑线乌梢蛇", latinName: "Ptyas nigromarginatus", morph: "Primary color", size: "Baby", priceUsd: "500", stock: 5 },
  { category: "chinese_snake", groupName: "Ptyas nigromarginatus", chineseName: "黑线乌梢蛇", latinName: "Ptyas nigromarginatus", morph: "Primary color", size: "Adult", priceUsd: "400", stock: 5 },
  { category: "chinese_snake", groupName: "Elaphe moellendorffi", chineseName: "百花锦蛇", latinName: "Elaphe moellendorffi", morph: "Primary color", size: "Adult", priceUsd: "100", stock: 10 },
  { category: "chinese_snake", groupName: "Elaphe moellendorffi", chineseName: "百花锦蛇", latinName: "Elaphe moellendorffi", morph: "Primary color", size: "Baby", priceUsd: "200", stock: 8 },
  { category: "chinese_snake", groupName: "Elaphe schrenckii", chineseName: "棕黑锦蛇", latinName: "Elaphe schrenckii", morph: "Primary color", size: "Baby", priceUsd: "50", stock: 20 },
  { category: "chinese_snake", groupName: "Elaphe schrenckii", chineseName: "棕黑锦蛇", latinName: "Elaphe schrenckii", morph: "Primary color", size: "Adult", priceUsd: "100", stock: 12 },
  { category: "chinese_snake", groupName: "Elaphe schrenckii", chineseName: "棕黑锦蛇", latinName: "Elaphe schrenckii", morph: "Patternless", size: "Adult", priceUsd: "500", stock: 3 },
  { category: "chinese_snake", groupName: "Elaphe schrenckii", chineseName: "棕黑锦蛇", latinName: "Elaphe schrenckii", morph: "Melanistic", size: "Adult", priceUsd: "2000", showPrice: false, stock: 1 },
  { category: "chinese_snake", groupName: "Lycodon rufozonatus", chineseName: "赤链蛇", latinName: "Lycodon rufozonatus", morph: "Primary color", size: "Adult", priceUsd: "100", stock: 15 },
  { category: "chinese_snake", groupName: "Lycodon flavozonatum", chineseName: "黄链蛇", latinName: "Lycodon flavozonatum", morph: "Primary color", size: "Adult", priceUsd: "100", stock: 10 },
  { category: "chinese_snake", groupName: "Lycodon rosozonatum", chineseName: "粉链蛇", latinName: "Lycodon rosozonatum", morph: "Primary color", size: "Adult", priceUsd: "500", stock: 4, featured: true },
  { category: "chinese_snake", groupName: "Elaphe taeniura", chineseName: "黑眉锦蛇", latinName: "Elaphe taeniura", morph: "Primary color", size: "Adult", priceUsd: "100", stock: 12 },
  { category: "chinese_snake", groupName: "Elaphe taeniura", chineseName: "黑眉锦蛇", latinName: "Elaphe taeniura", morph: "Vietnamese", size: "Adult", priceUsd: "500", stock: 4 },
  { category: "chinese_snake", groupName: "Ptyas major", chineseName: "翠青蛇", latinName: "Ptyas major", morph: "Primary color", size: "Adult", priceUsd: "80", stock: 10 },
  { category: "chinese_snake", groupName: "Boiga guangxiensis", chineseName: "广西林蛇", latinName: "Boiga guangxiensis", morph: "Primary color", size: "Adult", priceUsd: "200", stock: 6 },
  { category: "chinese_snake", groupName: "Elaphe xiphodonta", chineseName: "秦皇锦蛇", latinName: "Elaphe xiphodonta", morph: "Primary color", size: "Adult", priceUsd: null, showPrice: false, stock: 0 },
  { category: "chinese_snake", groupName: "Archelaphe bella", chineseName: "方花蛇", latinName: "Archelaphe bella", morph: "Primary color", size: "Adult", priceUsd: "2000", showPrice: false, stock: 2 },
  { category: "chinese_snake", groupName: "Pseudoxenodon macrops", chineseName: "大眼斜鳞蛇", latinName: "Pseudoxenodon macrops", morph: "Primary color", size: "Adult", priceUsd: "200", stock: 8 },
  { category: "chinese_snake", groupName: "Pseudoxenodon bambusicola", chineseName: "横纹斜鳞蛇", latinName: "Pseudoxenodon bambusicola", morph: "Primary color", size: "Adult", priceUsd: "200", stock: 8 },
  { category: "chinese_snake", groupName: "Pseudoagkistrodon rudis", chineseName: "颈棱蛇", latinName: "Pseudoagkistrodon rudis", morph: "Primary color", size: "Adult", priceUsd: "200", stock: 8 },
  { category: "chinese_snake", groupName: "Oreocryptophis porphyraceus", chineseName: "紫灰锦蛇", latinName: "Oreocryptophis porphyraceus", morph: "Primary color", size: "Adult", priceUsd: "150", stock: 10 },
  { category: "chinese_snake", groupName: "Gonyosoma frenatum", chineseName: "灰腹绿锦", latinName: "Gonyosoma frenatum", morph: "Primary color", size: "Adult", priceUsd: "300", stock: 6 },
  { category: "chinese_snake", groupName: "Euprepiophis mandarina", chineseName: "玉斑锦蛇", latinName: "Euprepiophis mandarina", morph: "Primary color", size: "Adult", priceUsd: "100", stock: 10 },
  { category: "chinese_snake", groupName: "Euprepiophis mandarina", chineseName: "玉斑锦蛇", latinName: "Euprepiophis mandarina", morph: "Red", size: "Adult", priceUsd: "200", stock: 6 },
  { category: "chinese_snake", groupName: "Oligodon chinensis", chineseName: "中华小头蛇", latinName: "Oligodon chinensis", morph: "Primary color", size: "Adult", priceUsd: "100", stock: 10 },
  { category: "chinese_snake", groupName: "Elaphe dione", chineseName: "白条锦蛇", latinName: "Elaphe dione", morph: "Primary color", size: "Adult", priceUsd: "100", stock: 12 },
  // ---- Venomous ----
  { category: "venomous", groupName: "Bungarus fasciatus", chineseName: "金环蛇", latinName: "Bungarus fasciatus", morph: "Primary color", size: "Adult", priceUsd: "400", showPrice: false, venomous: true, citesAppendix: "II", stock: 4 },
  { category: "venomous", groupName: "Bungarus multicinctus", chineseName: "银环蛇", latinName: "Bungarus multicinctus", morph: "Primary color", size: "Adult", priceUsd: "200", showPrice: false, venomous: true, citesAppendix: "II", stock: 6 },
  { category: "venomous", groupName: "Deinagkistrodon acutus", chineseName: "尖吻蝮", latinName: "Deinagkistrodon acutus", morph: "Primary color", size: "Adult", priceUsd: "300", showPrice: false, venomous: true, citesAppendix: "II", stock: 5, featured: true },
  { category: "venomous", groupName: "Gloydius brevicaudus", chineseName: "短尾蝮", latinName: "Gloydius brevicaudus", morph: "Primary color", size: "Adult", priceUsd: "200", showPrice: false, venomous: true, stock: 6 },
  { category: "venomous", groupName: "Trimeresurus spp.", chineseName: "竹叶青", latinName: "Trimeresurus spp.", morph: "Primary color", size: "Adult", priceUsd: "100", showPrice: false, venomous: true, stock: 8 },
  { category: "venomous", groupName: "Naja atra", chineseName: "舟山眼镜蛇", latinName: "Naja atra", morph: "Primary color", size: "Baby", priceUsd: "50", showPrice: false, venomous: true, citesAppendix: "II", stock: 15 },
  { category: "venomous", groupName: "Naja atra", chineseName: "舟山眼镜蛇", latinName: "Naja atra", morph: "Primary color", size: "Adult", priceUsd: "100", showPrice: false, venomous: true, citesAppendix: "II", stock: 10 },
  { category: "venomous", groupName: "Naja atra", chineseName: "舟山眼镜蛇", latinName: "Naja atra", morph: "Albino", size: "Baby / Adult", priceUsd: "400", showPrice: false, venomous: true, citesAppendix: "II", stock: 5 },
  { category: "venomous", groupName: "Naja atra", chineseName: "舟山眼镜蛇", latinName: "Naja atra", morph: "Pandora", size: "Baby / Adult", priceUsd: "600", showPrice: false, venomous: true, citesAppendix: "II", stock: 3 },
  { category: "venomous", groupName: "Naja atra", chineseName: "舟山眼镜蛇", latinName: "Naja atra", morph: "Panda", size: "Adult", priceUsd: "1200", showPrice: false, venomous: true, citesAppendix: "II", stock: 2 },
  { category: "venomous", groupName: "Naja atra", chineseName: "舟山眼镜蛇", latinName: "Naja atra", morph: "Melanistic", size: "Baby", priceUsd: "2000", showPrice: false, venomous: true, citesAppendix: "II", stock: 1 },
  { category: "venomous", groupName: "Naja atra", chineseName: "舟山眼镜蛇", latinName: "Naja atra", morph: "Scaleless", size: "Baby", priceUsd: "10000", showPrice: false, venomous: true, citesAppendix: "II", stock: 1, featured: true },
  { category: "venomous", groupName: "Protobothrops jerdonii", chineseName: "菜花原矛头蝮", latinName: "Protobothrops jerdonii", morph: "Primary color", size: "Adult", priceUsd: "1500", showPrice: false, venomous: true, stock: 2 },
  { category: "venomous", groupName: "Rhabdophis tigrinus", chineseName: "虎斑颈槽蛇", latinName: "Rhabdophis tigrinus", morph: "Primary color", size: "Adult", priceUsd: "100", showPrice: false, venomous: true, stock: 10 },
  { category: "venomous", groupName: "Rhabdophis tigrinus", chineseName: "虎斑颈槽蛇", latinName: "Rhabdophis tigrinus", morph: "Blue", size: "Adult", priceUsd: "500", showPrice: false, venomous: true, stock: 3 },
  { category: "venomous", groupName: "Rhabdophis subminiatus", chineseName: "红脖颈槽蛇", latinName: "Rhabdophis subminiatus", morph: "Primary color", size: "Adult", priceUsd: "200", showPrice: false, venomous: true, stock: 6 },
  // ---- Chinese lizards ----
  { category: "lizard", groupName: "Calotes jerdoni", chineseName: "绿背树蜥", latinName: "Calotes jerdoni", morph: "Primary color", size: "Adult", priceUsd: "100", stock: 10 },
  { category: "lizard", groupName: "Calotes mystaceus", chineseName: "白唇树蜥", latinName: "Calotes mystaceus", morph: "Primary color", size: "Adult", priceUsd: "100", stock: 10 },
  { category: "lizard", groupName: "Calotes versicolor", chineseName: "变色树蜥", latinName: "Calotes versicolor", morph: "Primary color", size: "Adult", priceUsd: "50", stock: 20 },
  { category: "lizard", groupName: "Diploderma splendidum", chineseName: "丽纹龙蜥", latinName: "Diploderma splendidum", morph: "Primary color", size: "Adult", priceUsd: "100", stock: 12 },
  { category: "lizard", groupName: "Eremias przewalskii", chineseName: "虎纹捷蜥", latinName: "Eremias przewalskii", morph: "Primary color", size: "Adult", priceUsd: "50", stock: 15 },
  { category: "lizard", groupName: "Plestiodon chinensis", chineseName: "中华石龙子", latinName: "Plestiodon chinensis", morph: "Primary color", size: "Adult", priceUsd: "50", stock: 15 },
  { category: "lizard", groupName: "Eumeces elegans", chineseName: "三线石龙子", latinName: "Plestiodon elegans", morph: "Primary color", size: "Adult", priceUsd: "50", stock: 15 },
  // ---- International pet species ----
  { category: "pet_snake", groupName: "Heterodon nasicus", chineseName: "猪鼻蛇", latinName: "Heterodon nasicus", morph: "Albino", size: "Baby", priceUsd: "100/pr", stock: 10, featured: true },
  { category: "pet_snake", groupName: "Heterodon nasicus", chineseName: "猪鼻蛇", latinName: "Heterodon nasicus", morph: "Albino Conda", size: "Baby", priceUsd: "120/pr", stock: 8 },
  { category: "pet_snake", groupName: "Heterodon nasicus", chineseName: "猪鼻蛇", latinName: "Heterodon nasicus", morph: "Albino Super Conda", size: "Baby", priceUsd: "150/pr", stock: 8 },
  { category: "pet_snake", groupName: "Heterodon nasicus", chineseName: "猪鼻蛇", latinName: "Heterodon nasicus", morph: "Snow", size: "Baby", priceUsd: "160/pr", stock: 6 },
  { category: "pet_snake", groupName: "Heterodon nasicus", chineseName: "猪鼻蛇", latinName: "Heterodon nasicus", morph: "Snow Super Conda", size: "Baby", priceUsd: "400/pr", stock: 4 },
  { category: "pet_snake", groupName: "Heterodon nasicus", chineseName: "猪鼻蛇", latinName: "Heterodon nasicus", morph: "Super Arctic", size: "Baby", priceUsd: "220/pr", stock: 6 },
  { category: "pet_snake", groupName: "Heterodon nasicus", chineseName: "猪鼻蛇", latinName: "Heterodon nasicus", morph: "Super Arctic Conda", size: "Baby", priceUsd: "230/pr", stock: 6 },
  { category: "pet_snake", groupName: "Heterodon nasicus", chineseName: "猪鼻蛇", latinName: "Heterodon nasicus", morph: "Super Arctic Super Conda", size: "Baby", priceUsd: "250/pr", stock: 4 },
  { category: "pet_snake", groupName: "Heterodon nasicus", chineseName: "猪鼻蛇", latinName: "Heterodon nasicus", morph: "Leucistic", size: "Baby", priceUsd: "1000/pr", showPrice: false, stock: 2 },
  { category: "pet_snake", groupName: "Heterodon nasicus", chineseName: "猪鼻蛇", latinName: "Heterodon nasicus", morph: "Super Arctic Leucistic", size: "Baby", priceUsd: "3000/pr", showPrice: false, stock: 1 },
  { category: "pet_snake", groupName: "Pantherophis guttatus", chineseName: "玉米蛇", latinName: "Pantherophis guttatus", morph: "Normal", size: "Baby", priceUsd: "10/pc", stock: 50, featured: true },
  { category: "pet_snake", groupName: "Pantherophis guttatus", chineseName: "玉米蛇", latinName: "Pantherophis guttatus", morph: "Amelanistic (Amel)", size: "Baby", priceUsd: "30/pc", stock: 30 },
  { category: "pet_snake", groupName: "Pantherophis guttatus", chineseName: "玉米蛇", latinName: "Pantherophis guttatus", morph: "Snow", size: "Baby", priceUsd: "30/pc", stock: 20 },
  { category: "pet_snake", groupName: "Pantherophis guttatus", chineseName: "玉米蛇", latinName: "Pantherophis guttatus", morph: "Blizzard", size: "Baby", priceUsd: "40/pc", stock: 15 },
  { category: "pet_snake", groupName: "Pantherophis guttatus", chineseName: "玉米蛇", latinName: "Pantherophis guttatus", morph: "Sunglow", size: "Baby", priceUsd: "40/pc", stock: 15 },
  { category: "pet_snake", groupName: "Pantherophis guttatus", chineseName: "玉米蛇", latinName: "Pantherophis guttatus", morph: "Palmetto", size: "Baby", priceUsd: "100/pc", stock: 8 },
  { category: "pet_snake", groupName: "Pantherophis guttatus", chineseName: "玉米蛇", latinName: "Pantherophis guttatus", morph: "Base Scaleless", size: "Baby", priceUsd: "100/pc", stock: 8 },
  { category: "pet_snake", groupName: "Pantherophis guttatus", chineseName: "玉米蛇", latinName: "Pantherophis guttatus", morph: "Albino Scaleless", size: "Baby", priceUsd: "150/pc", stock: 6 },
  { category: "pet_snake", groupName: "Lampropeltis getula nigrita", chineseName: "墨西哥黑王", latinName: "Lampropeltis nigrita", morph: "Normal", size: "Baby", priceUsd: "150/pc", stock: 10, featured: true },
  { category: "pet_snake", groupName: "Lampropeltis getula nigrita", chineseName: "无鳞黑王", latinName: "Lampropeltis nigrita", morph: "Scaleless", size: "Baby", priceUsd: "30000/pc", showPrice: false, stock: 1, featured: true },
  { category: "pet_snake", groupName: "Lampropeltis californiae", chineseName: "加州王蛇", latinName: "Lampropeltis californiae", morph: "California Kingsnake (assorted)", size: "Baby", priceUsd: "20/pc", stock: 40 },
  { category: "pet_snake", groupName: "Lampropeltis californiae", chineseName: "加州王蛇", latinName: "Lampropeltis californiae", morph: "Banded / Black & White", size: "Baby", priceUsd: "30/pc", stock: 20 },
  { category: "pet_snake", groupName: "Lampropeltis californiae", chineseName: "加州王蛇", latinName: "Lampropeltis californiae", morph: "Premium AX White-sided", size: "Baby", priceUsd: "80/pc", stock: 8 },
  { category: "pet_snake", groupName: "Elaphe obsoleta", chineseName: "白娘娘", latinName: "Pantherophis obsoletus", morph: "Leucistic", size: "Baby", priceUsd: "50/pc", stock: 12 },
  { category: "pet_snake", groupName: "Elaphe obsoleta", chineseName: "白娘娘", latinName: "Pantherophis obsoletus", morph: "Scaleless Leucistic", size: "Baby", priceUsd: "200/pc", stock: 6 },
  { category: "gecko", groupName: "Eublepharis macularius", chineseName: "豹纹守宫", latinName: "Eublepharis macularius", morph: "Common morph", size: "Baby / Adult", priceUsd: "10/pc", stock: 50, featured: true },
  { category: "gecko", groupName: "Eublepharis macularius", chineseName: "豹纹守宫", latinName: "Eublepharis macularius", morph: "Black Night", size: "Baby / Subadult", priceUsd: "250/pc", stock: 5 },
  { category: "gecko", groupName: "Eublepharis macularius", chineseName: "豹纹守宫", latinName: "Eublepharis macularius", morph: "High-orange", size: "Baby / Subadult", priceUsd: "200/pc", stock: 6 },
  { category: "gecko", groupName: "Hemitheconyx caudicinctus", chineseName: "肥尾守宫", latinName: "Hemitheconyx caudicinctus", morph: "Common morph", size: "Baby / Adult", priceUsd: "15/pc", stock: 40 },
  { category: "gecko", groupName: "Hemitheconyx caudicinctus", chineseName: "肥尾守宫", latinName: "Hemitheconyx caudicinctus", morph: "One morph", size: "Baby / Subadult", priceUsd: "60/pc", stock: 15 },
  { category: "gecko", groupName: "Hemitheconyx caudicinctus", chineseName: "肥尾守宫", latinName: "Hemitheconyx caudicinctus", morph: "Three morph", size: "Baby / Subadult", priceUsd: "300/pc", stock: 5 },
  { category: "gecko", groupName: "Nephrurus levis", chineseName: "细皮瘤尾守宫", latinName: "Nephrurus levis", morph: "Albino Patternless", size: "Subadult / Adult", priceUsd: "80/pc", stock: 6 },
  { category: "lizard", groupName: "Pogona vitticeps", chineseName: "鬃狮蜥", latinName: "Pogona vitticeps", morph: "Red", size: "15cm", priceUsd: "40/pc", stock: 20 },
  { category: "lizard", groupName: "Pogona vitticeps", chineseName: "鬃狮蜥", latinName: "Pogona vitticeps", morph: "Citrus", size: "15cm", priceUsd: "50/pc", stock: 15 },
  { category: "lizard", groupName: "Pogona vitticeps", chineseName: "鬃狮蜥", latinName: "Pogona vitticeps", morph: "Zero", size: "15cm", priceUsd: "50/pc", stock: 15 },
  { category: "other", groupName: "Litoria caerulea", chineseName: "老爷树蛙", latinName: "Ranoidea caerulea", morph: "Green", size: "2cm", priceUsd: "3/pc", stock: 100 },
  { category: "other", groupName: "Litoria caerulea", chineseName: "老爷树蛙", latinName: "Ranoidea caerulea", morph: "Blue Snowflake", size: "2cm", priceUsd: "8/pc", stock: 50 },
  { category: "other", groupName: "Trachycephalus resinifictrix", chineseName: "牛奶蛙", latinName: "Trachycephalus resinifictrix", morph: "Normal morph", size: "2-3cm", priceUsd: "20/pc", stock: 40 },
];

async function seed() {
  const db = getDb();
  const existing = await db.select().from(species);
  if (existing.length > 0) {
    console.log(`Skip seed: ${existing.length} rows already exist.`);
    return;
  }
  await db.insert(species).values(rows);
  console.log(`Seeded ${rows.length} species rows.`);
}

seed().then(() => process.exit(0)).catch((e) => { console.error(e); process.exit(1); });
